version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    image: votingbuck-backend_server
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/.env
      # - ./:/app
      # - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    environment:
      NODE_ENV: production
      PORT: 3000

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
