tags:
  - name: Organizations
    description: Organization API

paths:
  # [GET] organization/id
  /organizations/{id}:
    get:
      tags:
        - Organizations
      summary: Find User By Id
      parameters:
        - name: id
          in: path
          description: Organization Id
          required: true
          type: integer
          schema:

      responses:
        200:
          description: 'OK'
          schema:
            type: object
            properties:
              orgInfo:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 42
                    name:
                      type: string
                      example: Walmart
                    industry:
                      type: string
                      example: school
              donationsByMonth:
                type: array
                items:
                  type: object
                  properties:
                    month_start_date:
                      type: string
                      example: 2012-12-01T00:00:00.000Z
                    amount_donated:
                      type: float
                      example: 12345.67
              topDonators:
                type: array
                items:
                  type: object
                  properties:
                    contributor:
                      type: string
                      example: John Smith
                    total_amount:
                      type: float
                      example: 12345.67
        404:
          description: 'Not Found'
        500:
          description: 'Server Error'

schemes:
  - https
  - http
